nginx_version: -1.16.1

nginx_user: nginx
worker_processes: auto
worker_connections: 1024
client_max_body_size: 4M
server_name: prepost.ru
proxy_pass: http://localhost:8085
upstream_name: auth-service
upstream_protocol: http://

ssl_certificate_name: prepost_ru.crt
ssl_certificate_key_name: prepost_ru.key
ssl_certificate_path: /etc/ssl/certs
ssl_certificate_key_path: /etc/ssl/private

nginx_conf_target_file: /etc/nginx/nginx.conf

child_node_template_file: child_node.conf
loadbalancer_template_file: loadbalancer_node.conf