- name: install java
  yum:
    name: "java{{ java_version }}"
    state: present

- name: create application folder
  file:
    path: "{{ application_path }}"
    state: directory

- name: copy system unit config
  template: 
    src: "{{ role_path }}/templates/{{ system_unit_file_name }}"
    dest: "{{ system_unit_dest_path }}/{{ system_unit_file_name }}"
    force: yes
    mode: 0755
  notify: reload daemons

- name: copy system unit environment vars file
  template: 
    src: "{{ role_path }}/templates/{{ system_unit_env_var_file_name }}"
    dest: "{{ system_unit_dest_path }}/{{ system_unit_env_var_file_name }}"
    force: yes
    mode: 0755
  notify: reload daemons

- name: get gitlab job name
  uri:
    url: "https://gitlab.com/api/v4/projects/{{ gitlab_project }}/jobs"
    headers:
      PRIVATE-TOKEN: "{{ gitlab_token }}"
  register: gitlab_build

- name: gitlab download artifact
  get_url:
    url: "https://gitlab.com/api/v4/projects/{{ gitlab_project }}/jobs/{{ gitlab_build.json[0].id }}/{{ file_path_in_artifact }}/{{ application_file_name }}"
    headers:
      PRIVATE-TOKEN: "{{ gitlab_token }}"
    dest: "{{ application_path }}/{{ application_file_name }}"
  notify: "restart {{ service_name }}"

- name: change gitlab artifact permission attributes
  file:
    path: "{{ application_path }}/{{ application_file_name }}"
    mode: 0755

- name: enable and start {{  service_name }}
  systemd: 
    name: "{{ service_name }}"
    daemon_reload: yes
    enabled: yes
    state: started
 