- name: install java
  yum:
    name: "java{{ java_version }}"
    state: present

- name: create java folder for symlink
  file: 
    path: "{{ java_folder_for_symlink }}"
    state: directory
    mode: 0755

- name: create symlink
  file: 
    src: "{{ java_folder }}"
    dest: "{{ java_folder_for_symlink }}/{{ java_symlink }}"
    state: link