- name: create java folder
  file: 
    path: /usr/java/
    state: directory
- name: copy java distr
  copy:
    src: /usr/java/jdk-9.0.4_linux-x64_bin.rpm 
    dest: /usr/java/
    force: yes
    mode: 755
- name: install java
  yum:
    name: /usr/java/jdk-9.0.4_linux-x64_bin.rpm 
    state: present
- name: set java_home
  lineinfile: 
    dest: /etc/profile 
    regexp: '^JAVA_HOME'
    line: "export JAVA_HOME=/usr/java/jdk-9.0.4"
- name: set path
  lineinfile: 
    dest: /etc/profile 
    regexp: '^PATH='
    line: "export PATH=$PATH:/usr/java/jdk-9.0.4/bin"
- name: reload env vars
  shell: source /etc/profile
