- name: install postgresql repo
  yum:
    name: "{{ postgresql_repo_url }}"

- name: install postgresql
  yum: 
    name: "['{{ postgresql_version }}', 'python-psycopg2']"
    state: present
    allow_downgrade: yes